version: '3.5'

services:
  frontend:
    image: ghcr.io/unizar-30226-2021-03/frontend/keypax-react-app:stable
    networks:
      - frontend
  nginx-proxy:
    image: ghcr.io/unizar-30226-2021-03/frontend/nginx-certbot:stable 
    environment:
      - CERTBOT_EMAIL=${email}
    volumes:
      - nginx_secrets:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    depends_on:
      - frontend  
networks:
  frontend:
    driver: bridge
volumes:
  nginx_secrets: